In [13]:
import numpy as np
import pandas as pd
from pandas import Series , DataFrame


In [30]:
dframe = DataFrame({'key':['x','z','y','z','x','x'], 'dat_set':np.arange(6) })

In [31]:
dframe

dat_set key
0        0   x
1        1   z
2        2   y
3        3   z
4        4   x
5        5   x

In [32]:
dframe2 = DataFrame({'key':['q','y','z'] , 'data_set2':[1,2,3]})

In [33]:
dframe2

data_set2 key
0          1   q
1          2   y
2          3   z

In [34]:
pd.merge(dframe, dframe2)

dat_set key  data_set2
0        1   z          3
1        3   z          3
2        2   y          2

In [36]:
pd.merge(dframe,dframe2,on='key',how='right')

dat_set key  data_set2
0      1.0   z          3
1      3.0   z          3
2      2.0   y          2
3      NaN   q          1

In [37]:
pd.merge(dframe,dframe2,how='outer')

dat_set key  data_set2
0      0.0   x        NaN
1      4.0   x        NaN
2      5.0   x        NaN
3      1.0   z        3.0
4      3.0   z        3.0
5      2.0   y        2.0
6      NaN   q        1.0

In [38]:
df_left = DataFrame({'Key1':['SF','SF','LA'], 'Key2':['one','two','one'],'left_data':[10,20,30]})

In [39]:
df_right = DataFrame({'Key1':['SF','SF','LA','LA'] , 'Key2':['one','one','one','two'] , 'right_data':[40,50,60,70]})

In [40]:
df_left


Key1 Key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [41]:
df_right

Key1 Key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [49]:
#pd.merge(df_left,df_right)

In [54]:
#pd.merge(df_left,df_right , on=['Key1','Key2'])

In [53]:
pd.merge(df_left , df_right , on='Key1')

Key1 Key2_x  left_data Key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

# Merging on Index

In [56]:
df_left = DataFrame({'Key':['x','y','z','x','y'] , 'data': range(5)})

In [57]:
df_left

Key  data
0   x     0
1   y     1
2   z     2
3   x     3
4   y     4

In [59]:
df_right = DataFrame({'groupdata':[10,20] }, index=['x','y'])

In [60]:
df_right

groupdata
x         10
y         20

In [75]:
pd.merge(df_left , df_right ,left_on = 'Key' , right_index = True)

Key  data  groupdata
0   x     0         10
3   x     3         10
1   y     1         20
4   y     4         20

# combining dataframe

In [76]:
ser1 =Series([2,np.nan,4,np.nan,6,np.nan] , index=['q','r','s','t','u','v'])

In [77]:
ser2 = Series(np.arange(6),index=['q','r','s','t','u','v'])

In [89]:
Combined = Series(np.where(pd.isnull(ser1),ser2,ser1) , index=ser1.index)

In [94]:
#Same command
print Combined
print ser1.combine_first(ser2)

q    2.0
r    1.0
s    4.0
t    3.0
u    6.0
v    5.0
dtype: float64
q    2.0
r    1.0
s    4.0
t    3.0
u    6.0
v    5.0
dtype: float64


In [96]:
pd.concat([ser1,ser2])

q    2.0
r    NaN
s    4.0
t    NaN
u    6.0
v    NaN
q    0.0
r    1.0
s    2.0
t    3.0
u    4.0
v    5.0
dtype: float64

In [97]:
pd.concat([ser1,ser2],axis=1)

0  1
q  2.0  0
r  NaN  1
s  4.0  2
t  NaN  3
u  6.0  4
v  NaN  5

 # RESHAPING

In [102]:
dframe = DataFrame(np.arange(8).reshape(2,4) , index=pd.Index(['LA','SF'] , name='city'),columns=pd.Index(['A','B','C','D'],
                                                                                                         name='letters'))

In [103]:
dframe

letters  A  B  C  D
city               
LA       0  1  2  3
SF       4  5  6  7

In [106]:
dframe_st = dframe.stack()

In [107]:
dframe_st

city  letters
LA    A          0
      B          1
      C          2
      D          3
SF    A          4
      B          5
      C          6
      D          7
dtype: int32

In [108]:
dframe_st.unstack()

letters  A  B  C  D
city               
LA       0  1  2  3
SF       4  5  6  7

In [110]:
dframe1 =dframe_st.unstack('city')

In [111]:
dframe1

city     LA  SF
letters        
A         0   4
B         1   5
C         2   6
D         3   7

In [113]:
dframe1.stack()

letters  city
A        LA      0
         SF      4
B        LA      1
         SF      5
C        LA      2
         SF      6
D        LA      3
         SF      7
dtype: int32

In [114]:
ser1= Series([0,1,2] , index=['Q','X','Y']
            )

In [115]:
ser2=Series([4,5,6],index=['X','Y','Z'])

In [119]:
ser=pd.concat([ser1,ser2],keys=['alpha','beta'])

In [120]:
ser

alpha  Q    0
       X    1
       Y    2
beta   X    4
       Y    5
       Z    6
dtype: int64

In [121]:
ser.unstack()

Q    X    Y    Z
alpha  0.0  1.0  2.0  NaN
beta   NaN  4.0  5.0  6.0

In [125]:
ser.unstack(level=0)

alpha  beta
Q    0.0   NaN
X    1.0   4.0
Y    2.0   5.0
Z    NaN   6.0

# Duplicates in DATAFRAMES

In [126]:
dframe= DataFrame({'key1':['A']*2+['B']*3, 'Key2': [2,2,2,3,3]})

In [127]:
dframe

Key2 key1
0     2    A
1     2    A
2     2    B
3     3    B
4     3    B

In [128]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [131]:
#get rid of duplicates
dframe.drop_duplicates()

Key2 key1
0     2    A
2     2    B
3     3    B

In [133]:
dframe.drop_duplicates('Key2')

Key2 key1
0     2    A
3     3    B

# Mapping

In [136]:
dframe = DataFrame({'city':['Alma','Brian Head','Fox Park'],'altitude':[3158,3000,2762]})

In [137]:
dframe

altitude        city
0      3158        Alma
1      3000  Brian Head
2      2762    Fox Park

In [138]:
state_map = {'Alma':'Corolado', 'Brian Head':'Utah' , 'Fox Park':'Miami'}

In [139]:
dframe['states'] =dframe['city'].map(state_map)

In [140]:
dframe

altitude        city    states
0      3158        Alma  Corolado
1      3000  Brian Head      Utah
2      2762    Fox Park     Miami

# Replace

In [144]:
ser1 = Series([1,2,3,4,1,2,3,4] )

In [145]:
ser1


0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [148]:
print ser1.replace(1,np.nan)
print ser1.replace([1,4],[100,400])

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64
0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64


In [150]:
dframe=DataFrame(np.arange(16).reshape(4,4))

In [151]:
blender = np.random.permutation(4)

In [152]:
blender

array([0, 3, 1, 2])

In [153]:
dframe.take(blender)

0   1   2   3
0   0   1   2   3
3  12  13  14  15
1   4   5   6   7
2   8   9  10  11

In [154]:
box = np.array([1,2,3])

In [155]:
shaker = np.random.randint(0,len(box),size=10)

In [156]:
shaker

array([1, 0, 0, 1, 0, 2, 1, 2, 1, 0])

In [157]:
box.take(shaker)

array([2, 1, 1, 2, 1, 3, 2, 3, 2, 1])